from . import propriete_views
from . import location_views
from . import locataire_views
from . import etats_des_lieux_views
from . import facture_views
from . import rappel_views
from . import estate_menu
from . import commodite_views
from . import vues_additionnelles
from . import action_updates 